import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage');
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(e){$('error').hidden=false;$('error').textContent='The 3D renderer could not start: '+e.message;throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe6ede9);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.localClippingEnabled=true;stage.prepend(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.05,1500);camera.up.set(0,0,1);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.screenSpacePanning=true;controls.minDistance=2;controls.maxDistance=450;controls.enableZoom=true;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;
scene.add(new THREE.HemisphereLight(0xf7fffb,0x57675d,2.1));for(const [pos,power]of [[[50,-70,110],3.2],[[-60,40,30],2.0],[[40,70,-30],1.1]]){let l=new THREE.DirectionalLight(0xffffff,power);l.position.set(...pos);scene.add(l)}
const assembly=new THREE.Group();scene.add(assembly);const contextCamera=new THREE.PerspectiveCamera(35,1,.1,1000);contextCamera.up.set(0,0,1);
let meshes=[],selected='lock',isolation=false,focus='lock',motion=true,lastStep=0,playStart=0,manual=false;
const params={length:40,travel:0,explode:0,actuation:0,full:true,pose:.65,angle:170,manual:false,paperThickness:3.6};
const group=name=>name.startsWith('Fixed actuator')||name.startsWith('Stop frame')?'stop':name.startsWith('Pawl')||name.startsWith('P shared')?'pawl':name.includes('spring')||name.includes('Spring')?'spring':name.includes('runner')||name==='Runner tooth'||name.startsWith('B ')?'runner':name.includes('Engager bar')||name.includes('actuator')||name.includes('Actuator')||name.startsWith('Candidate')?'actuator':name.startsWith('BC')?'coupler':name.startsWith('Wide jaw')||name.startsWith('Jaw')||name.startsWith('C shared')||name.startsWith('D shared')?'jaw':name.startsWith('Clipboard')||name.startsWith('Paper')||name.startsWith('Fixed')||name.startsWith('Backplate')||name.startsWith('E fixed')?'frame':'arm';
const belongs=(m,key)=>key==='lock'?['pawl','actuator','runner','spring'].includes(m.userData.group):m.userData.group===key;
function triangles(part){const indices=[];for(const face of part.f){if(face.length===3){indices.push(...face);continue}let normal=new THREE.Vector3();const a=new THREE.Vector3(...part.v[face[0]]);for(let i=1;i<face.length-1;i++){let b=new THREE.Vector3(...part.v[face[i]]).sub(a),c=new THREE.Vector3(...part.v[face[i+1]]).sub(a);normal.add(b.cross(c))}const abs=[Math.abs(normal.x),Math.abs(normal.y),Math.abs(normal.z)],drop=abs.indexOf(Math.max(...abs)),xy=face.map(i=>{const v=part.v[i].filter((_,j)=>j!==drop);return new THREE.Vector2(...v)});for(const tri of THREE.ShapeUtils.triangulateShape(xy,[]))indices.push(...tri.map(j=>face[j]));}return indices}
function rebuild(){
 for(const m of meshes){m.geometry.dispose();m.material.dispose();for(const c of m.children){c.geometry?.dispose();c.material?.dispose()}}assembly.clear();meshes=[];
 for(const p of buildScene(params)){const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(p.v.flat(),3));geom.setIndex(triangles(p));geom.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:p.color,metalness:.12,roughness:.56,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geom,mat);mesh.name=p.name;mesh.userData={group:group(p.name),kind:p.kind,color:p.color,centerY:p.v.reduce((s,v)=>s+v[1],0)/p.v.length};
 if(!p.name.includes('spring')){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geom,25),new THREE.LineBasicMaterial({color:0x34493e,transparent:true,opacity:.22}));mesh.add(edge)}
 assembly.add(mesh);meshes.push(mesh);
 }
 applyVisibility();$('phase').textContent=wholeState(params).phase;$('mode').textContent=params.manual?'Manual exploration — not a solved state.':'Prescribed cycle, not validated contact.';
}
function sidePlate(m){return /side |side plate|frame plate|BC fixed coupler/.test(m.name)}
function applyVisibility(){const mode=$('plates').value;for(const m of meshes){m.visible=m.userData.kind!=='candidate'&&m.userData.kind!=='cover';let op=1;if(sidePlate(m)){if(mode==='hidden'||mode==='cut'&&m.userData.centerY<0)m.visible=false;if(mode==='ghost')op=.12;if(mode==='cut'&&m.userData.centerY>0)op=.28}
 if(m.name.startsWith('Clipboard board')){op=$('board').value==='solid'?1:.12;if($('board').value==='hide')m.visible=false;}
 if(isolation&&!belongs(m,selected))m.visible=false;
 m.material.transparent=op<1;m.material.opacity=op;m.material.depthWrite=op===1;m.material.clippingPlanes=$('section').checked?[new THREE.Plane(new THREE.Vector3(0,1,0),0)]:[];m.material.emissive.setHex(selected!=='lock'&&belongs(m,selected)?0x433008:0);m.material.emissiveIntensity=.5;m.material.needsUpdate=true;
 for(const e of m.children)e.visible=op>.5||m.name.startsWith('Clipboard board');
 }}
function bounds(key){const b=new THREE.Box3();for(const m of meshes)if((key==='lock'?m.userData.group==='pawl'&&!m.name.startsWith('P shared'):(key==='whole'||belongs(m,key)))&&m.userData.kind!=='candidate')b.expandByObject(m);if(key==='lock')b.expandByScalar(3);if(key==='stop')b.expandByScalar(4);return b}
function fit(key='lock',direction=null){const b=bounds(key),c=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3());const radius=size.length()/2;const aspect=Math.min(1,camera.aspect),dist=radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))*1.18/aspect;const dir=direction||(key==='whole'?new THREE.Vector3(-1,-.65,.18):new THREE.Vector3(.28,-1,.18)).normalize();controls.target.copy(c);camera.position.copy(c).addScaledVector(dir,dist);camera.near=Math.max(.02,dist/1500);camera.far=Math.max(1000,dist*8);camera.updateProjectionMatrix();controls.update();}
$('paper').oninput=()=>{params.paperThickness=+$('paper').value;$('papervalue').textContent=params.paperThickness.toFixed(1)+' mm';rebuild()};
function setFocus(key){focus=key;$('lock').classList.toggle('active',key==='lock');$('whole').classList.toggle('active',key==='whole');fit(key)}
function select(key){selected=key;$('part').value=key;$('selectedname').textContent=($('part').selectedOptions[0]?.textContent||'Frame contact stop');$('selectionnote').textContent=key==='lock'?'Engager nose · pawl · moving teeth':'Click Fit selection to inspect this part';const editable=['actuator','pawl','runner','arm','coupler','jaw'].includes(key);$('movebox').hidden=!editable;
 if(editable){const a=key==='actuator'||key==='pawl',b=key==='runner';$('move').min=a?0:b?0:100;$('move').max=a?1:b?8:180;$('move').step=a?.01:.1;$('move').value=a?params.actuation:b?params.travel:params.angle;$('movelabel').textContent=a?'Illustrative actuator stroke':b?'B inward travel (mm)':'Handle angle (degrees)';$('movevalue').textContent=$('move').value;}applyVisibility();}
$('part').onchange=()=>select($('part').value);$('fit').onclick=()=>fit(selected);$('isolate').onclick=()=>{isolation=!isolation;$('isolate').classList.toggle('active',isolation);applyVisibility();fit(selected)};$('showall').onclick=()=>{isolation=false;$('isolate').classList.remove('active');applyVisibility()};$('lock').onclick=()=>{select('lock');isolation=false;applyVisibility();setFocus('lock')};$('whole').onclick=()=>{isolation=false;applyVisibility();setFocus('whole')};$('plates').onchange=applyVisibility;$('board').onchange=applyVisibility;$('section').onchange=applyVisibility;
$('view').onchange=()=>{const dirs={oblique:new THREE.Vector3(.28,-1,.18),side:new THREE.Vector3(0,-1,0),top:new THREE.Vector3(0,-.001,1),end:new THREE.Vector3(1,0,0)};fit(focus,dirs[$('view').value].normalize())};$('resetview').onclick=()=>setFocus('lock');$('drive').onclick=()=>{focus='stop';fit('stop');$('selectedname').textContent='Frame contact stop';$('selectionnote').textContent='The engager rear end meets this stationary stop'};
function zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update()}
$('zoomin').onclick=()=>zoom(.8);$('zoomout').onclick=()=>zoom(1.25);
// Trackpad adapter: ordinary two-finger wheel events pan; ctrl-wheel pinch zooms.
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();e.stopImmediatePropagation();if(e.ctrlKey){zoom(Math.exp(e.deltaY*.008));return}const distance=camera.position.distanceTo(controls.target),unit=2*distance*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/stage.clientHeight;camera.updateMatrix();const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrix,1),shift=right.multiplyScalar(-e.deltaX*unit).add(up.multiplyScalar(e.deltaY*unit));camera.position.add(shift);controls.target.add(shift);controls.update();},{passive:false,capture:true});
let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),v=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(v,camera);const hit=ray.intersectObjects(meshes.filter(m=>m.visible&&m.material.opacity>.3),false)[0];if(hit)select(hit.object.userData.group)});
$('move').oninput=()=>{motion=false;$('play').textContent='Play cycle';params.manual=true;const val=+$('move').value;if(selected==='actuator'||selected==='pawl')params.actuation=val;else if(selected==='runner')params.travel=val;else params.angle=val;$('movevalue').textContent=val;rebuild()};
$('pose').oninput=()=>{motion=false;$('play').textContent='Play cycle';params.manual=false;params.pose=+$('pose').value;rebuild()};$('resetpose').onclick=()=>{motion=false;$('play').textContent='Play cycle';params.manual=false;params.pose=0;$('pose').value=0;rebuild();fit(focus)};$('play').onclick=()=>{motion=!motion;$('play').textContent=motion?'Pause':'Play cycle';if(motion){params.manual=false;playStart=performance.now()-params.pose*16000}};
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);
function render(now){requestAnimationFrame(render);if(motion&&now-lastStep>65){lastStep=now;params.pose=((now-playStart)/16000)%1;$('pose').value=params.pose;rebuild();}controls.update();renderer.setScissorTest(false);renderer.setViewport(0,0,stage.clientWidth,stage.clientHeight);renderer.render(scene,camera);
 const w=stage.clientWidth,h=stage.clientHeight;if(w>650){const cw=145,ch=185;const b=bounds('whole'),c=b.getCenter(new THREE.Vector3());contextCamera.aspect=cw/ch;contextCamera.position.copy(c).add(new THREE.Vector3(-260,-330,70));contextCamera.lookAt(c);contextCamera.updateProjectionMatrix();renderer.clearDepth();renderer.setScissorTest(true);renderer.setScissor(w-cw-14,12,cw,ch);renderer.setViewport(w-cw-14,12,cw,ch);renderer.setClearColor(0xf6faf7);renderer.clear(true,true,false);renderer.render(scene,contextCamera);renderer.setScissorTest(false);renderer.setClearColor(0xe6ede9)}
}
rebuild();resize();select('lock');fit('lock');playStart=performance.now()-params.pose*16000;$('play').textContent='Pause';requestAnimationFrame(render);
