import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage');
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch(e){$('error').hidden=false;$('error').textContent='The 3D renderer could not start: '+e.message;throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe6ede9);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.localClippingEnabled=true;stage.prepend(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.05,1500);camera.up.set(0,0,1);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.screenSpacePanning=true;controls.minDistance=2;controls.maxDistance=1000;controls.enableZoom=true;controls.touches.TWO=THREE.TOUCH.DOLLY_PAN;
scene.add(new THREE.HemisphereLight(0xf7fffb,0x57675d,2.1));for(const [pos,power]of [[[50,-70,110],3.2],[[-60,40,30],2.0],[[40,70,-30],1.1]]){let l=new THREE.DirectionalLight(0xffffff,power);l.position.set(...pos);scene.add(l)}
const assembly=new THREE.Group();scene.add(assembly);const contextCamera=new THREE.PerspectiveCamera(35,1,.1,1000);contextCamera.up.set(0,0,1);
let meshes=[],selected='lock',isolation=false,focus='lock',motion=true,lastStep=0,playStart=0,manual=false,reveal=false,followCenter=null;
const params={length:40,travel:0,explode:0,actuation:0,full:true,pose:.65,angle:170,manual:false,paperThickness:3.6,checkTeeth:true,reference:!new URLSearchParams(location.search).has('legacy')};
const group=name=>name.startsWith('Fixed actuator')||name.startsWith('Stop frame')?'stop':name.startsWith('Pawl')||name.startsWith('P shared')?'pawl':name.includes('spring')||name.includes('Spring')?'spring':name.includes('runner')||name==='Runner tooth'||name.startsWith('B ')?'runner':name.includes('Engager bar')||name.includes('actuator')||name.includes('Actuator')||name.startsWith('Candidate')?'actuator':name.startsWith('BC')?'coupler':name.startsWith('Wide jaw')||name.startsWith('Jaw')||name.startsWith('C shared')||name.startsWith('D shared')?'jaw':name.startsWith('Clipboard')||name.startsWith('Paper')||name.startsWith('Fixed')||name.startsWith('Backplate')||name.startsWith('E fixed')?'frame':'arm';
const viewPoint=q=>params.reference?new THREE.Vector3(-q.z,-q.y,26.4-q.x):q;
const belongs=(m,key)=>key==='lock'?['pawl','actuator','runner','spring'].includes(m.userData.group):m.userData.group===key;
function triangles(part){const indices=[];for(const face of part.f){if(face.length===3){indices.push(...face);continue}let normal=new THREE.Vector3();const a=new THREE.Vector3(...part.v[face[0]]);for(let i=1;i<face.length-1;i++){let b=new THREE.Vector3(...part.v[face[i]]).sub(a),c=new THREE.Vector3(...part.v[face[i+1]]).sub(a);normal.add(b.cross(c))}const abs=[Math.abs(normal.x),Math.abs(normal.y),Math.abs(normal.z)],drop=abs.indexOf(Math.max(...abs)),xy=face.map(i=>{const v=part.v[i].filter((_,j)=>j!==drop);return new THREE.Vector2(...v)});for(const tri of THREE.ShapeUtils.triangulateShape(xy,[]))indices.push(...tri.map(j=>face[j]));}return indices}
function rebuild(){
 for(const m of meshes){m.geometry.dispose();m.material.dispose();for(const c of m.children){c.geometry?.dispose();c.material?.dispose()}}assembly.clear();meshes=[];
 for(const p of buildScene(params)){const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.Float32BufferAttribute(p.v.flat(),3));geom.setIndex(triangles(p));geom.computeVertexNormals();const mat=new THREE.MeshStandardMaterial({color:p.color,metalness:.12,roughness:.56,flatShading:true,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geom,mat);mesh.name=p.name;mesh.userData={group:group(p.name),kind:p.kind,color:p.color,centerY:p.v.reduce((s,v)=>s+v[1],0)/p.v.length};
 if(!p.name.includes('spring')){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geom,25),new THREE.LineBasicMaterial({color:0x34493e,transparent:true,opacity:.22}));mesh.add(edge)}
 assembly.add(mesh);meshes.push(mesh);
 }
 addCenterline();applyVisibility();if(reveal&&focus==='lock'){const c=bounds('lock').getCenter(new THREE.Vector3());if(followCenter){const delta=c.clone().sub(followCenter);camera.position.add(delta);controls.target.add(delta)}followCenter=c;}$('toothstatus').textContent=lastToothFit?.blocked?'Pawl sweep blocked with runner fixed':'Fixed-runner pawl sweep clear at this pose';$('toothdetail').textContent=lastToothFit?(lastToothFit.blocked?'Tooth path blocked: '+lastToothFit.reachablePhi.toFixed(1)+'° reachable / '+lastToothFit.commandedPhi.toFixed(1)+'° commanded':'Tooth path clear at this pose'):'';$('phase').textContent=wholeState(params).phase;$('handleangle').textContent='A: '+(wholeState(params).t*180/Math.PI).toFixed(1)+'°';$('mode').textContent=params.manual?'Manual exploration — not a solved state.':'Prescribed cycle, not validated contact.';
}
function addCenterline(){const st=wholeState(params),s=st.scale,project=q=>viewPoint(new THREE.Vector3((32-q[1])*s,0,(q[0]-44)*s+2.5)),A=project([44,32]),B=project(st.B),C=project(st.C),v=C.clone().sub(A),foot=A.clone().addScaledVector(v,B.clone().sub(A).dot(v)/v.lengthSq());for(const pts of [[A,C],[B,foot]]){const g=new THREE.BufferGeometry().setFromPoints(pts),m=new THREE.LineDashedMaterial({color:0x6e1e2c,dashSize:.6,gapSize:.4,depthTest:false,transparent:true,opacity:.85}),line=new THREE.Line(g,m);line.computeLineDistances();line.renderOrder=20;line.userData={kind:'centerline',group:'centerline'};assembly.add(line);meshes.push(line)}const ac=[st.C[0]-44,st.C[1]-32],ab=[st.B[0]-44,st.B[1]-32],d=(ac[0]*ab[1]-ac[1]*ab[0])/Math.hypot(...ac)*s;$('margin').textContent='B to A–C: '+d.toFixed(2)+' mm (signed)';}
function sidePlate(m){return /side |side plate|frame plate|BC fixed coupler/.test(m.name)}
function applyVisibility(){const mode=$('plates').value;for(const m of meshes){if(m.userData.kind==='centerline'){m.visible=$('centerline').checked&&!isolation;continue}m.visible=m.userData.kind!=='candidate'&&m.userData.kind!=='cover';let op=1;if(sidePlate(m)){if(mode==='hidden'||mode==='cut'&&m.userData.centerY<0)m.visible=false;if(mode==='ghost')op=.12;if(mode==='cut'&&m.userData.centerY>0)op=.28}
 if(reveal&&!belongs(m,'lock')&&!m.name.startsWith('Pawl support')&&!m.name.startsWith('Spring'))op=.055;
 if(m.name.startsWith('Clipboard board')){op=$('board').value==='solid'?1:.12;if($('board').value==='hide')m.visible=false;}
 if(isolation&&!belongs(m,selected))m.visible=false;
 m.material.transparent=op<1;m.material.opacity=op;m.material.depthWrite=op===1;m.material.clippingPlanes=$('section').checked?[new THREE.Plane(new THREE.Vector3(0,1,0),0)]:[];m.material.emissive.setHex(selected!=='lock'&&belongs(m,selected)?0x433008:0);m.material.emissiveIntensity=.5;m.material.needsUpdate=true;
 for(const e of m.children)e.visible=op>.5||m.name.startsWith('Clipboard board')||reveal&&m.userData.kind==='handle';
 }}
function bounds(key){const b=new THREE.Box3();for(const m of meshes)if((key==='lock'?belongs(m,'lock')&&!m.name.includes('shared')&&!m.name.includes('external'):(key==='whole'||belongs(m,key)))&&m.userData.kind!=='candidate')b.expandByObject(m);if(key==='lock')b.expandByScalar(3);if(key==='stop')b.expandByScalar(4);return b}
function fit(key='lock',direction=null){const b=bounds(key),c=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3());const radius=size.length()/2;const aspect=Math.min(1,camera.aspect),dist=radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))*1.18/aspect;const dir=direction||(params.reference?new THREE.Vector3(1,-1,.75):key==='whole'?new THREE.Vector3(-1,-.65,.18):new THREE.Vector3(.28,-1,.18)).normalize();controls.target.copy(c);camera.position.copy(c).addScaledVector(dir,dist);camera.near=Math.max(.02,dist/1500);camera.far=Math.max(1000,dist*8);camera.updateProjectionMatrix();controls.update();followCenter=key==='lock'?c.clone():null;}
$('layout').onchange=()=>{params.reference=$('layout').value==='reference';$('plates').value=params.reference?'solid':'cut';$('whole').textContent=params.reference?'Whole desk pad':'Whole clipboard';$('contextlabel').textContent=params.reference?'Desk-pad context':'Clipboard context';$('boardlabel').hidden=params.reference;renderer.toneMappingExposure=params.reference?.9:1.25;rebuild();fit(focus)};
$('transparent').onchange=()=>{reveal=$('transparent').checked;applyVisibility()};$('panelplay').onclick=()=>$('play').click();$('backwhole').onclick=()=>setFocus('whole');
$('checkteeth').onchange=()=>{params.checkTeeth=$('checkteeth').checked;rebuild()};
$('paper').oninput=()=>{params.paperThickness=+$('paper').value;$('papervalue').textContent=params.paperThickness.toFixed(1)+' mm';rebuild()};
function setFocus(key){if(key==='lock')stage.scrollIntoView({behavior:'smooth',block:'start'});focus=key;reveal=key==='lock';$('transparent').checked=reveal;followCenter=null;$('lock').textContent=reveal?'Mechanism shown':'Show mechanism';$('handleview').classList.toggle('active',key==='arm');applyVisibility();$('lock').classList.toggle('active',key==='lock');$('whole').classList.toggle('active',key==='whole');fit(key)}
function select(key){selected=key;$('part').value=key;$('selectedname').textContent=($('part').selectedOptions[0]?.textContent||'Frame contact stop');$('selectionnote').textContent=key==='lock'?'Proposed runner, pawl and engager · dimensions and strength unvalidated':'Click Fit selection to inspect this part';const editable=['actuator','pawl','runner','arm','coupler','jaw'].includes(key);$('movebox').hidden=!editable;
 if(editable){const a=key==='actuator'||key==='pawl',b=key==='runner';$('move').min=a?0:b?0:100;$('move').max=a?1:b?8:180;$('move').step=a?.01:.1;$('move').value=a?params.actuation:b?params.travel:params.angle;$('movelabel').textContent=a?'Illustrative actuator stroke':b?'B inward travel (mm)':'Handle angle (degrees)';$('movevalue').textContent=$('move').value;}applyVisibility();}
$('part').onchange=()=>select($('part').value);$('fit').onclick=()=>fit(selected);$('isolate').onclick=()=>{isolation=!isolation;$('isolate').classList.toggle('active',isolation);applyVisibility();fit(selected)};$('showall').onclick=()=>{isolation=false;$('isolate').classList.remove('active');applyVisibility()};$('lock').onclick=()=>{select('lock');isolation=false;applyVisibility();setFocus('lock')};$('whole').onclick=()=>{isolation=false;applyVisibility();setFocus('whole')};$('plates').onchange=applyVisibility;$('board').onchange=applyVisibility;$('section').onchange=applyVisibility;$('centerline').onchange=applyVisibility;
$('mechanismtop').onclick=()=>{select('lock');isolation=false;setFocus('lock');fit('lock',new THREE.Vector3(0,-.001,1).normalize())};
$('view').onchange=()=>{const dirs={oblique:new THREE.Vector3(.28,-1,.18),side:new THREE.Vector3(0,-1,0),top:new THREE.Vector3(0,-.001,1),end:new THREE.Vector3(1,0,0)};fit(focus,dirs[$('view').value].normalize())};$('resetview').onclick=()=>setFocus('lock');$('drive').onclick=()=>{focus='stop';fit('stop');$('selectedname').textContent='Frame contact stop';$('selectionnote').textContent='The engager rear end meets this stationary stop'};
function zoom(factor){camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update()}
$('zoomin').onclick=()=>zoom(.8);$('zoomout').onclick=()=>zoom(1.25);
// Trackpad adapter: ordinary two-finger wheel events pan; ctrl-wheel pinch zooms.
renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();e.stopImmediatePropagation();if(e.ctrlKey){zoom(Math.exp(e.deltaY*.008));return}const distance=camera.position.distanceTo(controls.target),unit=2*distance*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/stage.clientHeight;camera.updateMatrix();const right=new THREE.Vector3().setFromMatrixColumn(camera.matrix,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrix,1),shift=right.multiplyScalar(-e.deltaX*unit).add(up.multiplyScalar(e.deltaY*unit));camera.position.add(shift);controls.target.add(shift);controls.update();},{passive:false,capture:true});
// Direct handle interaction follows the existing illustrative linkage path.
let handleDrag=null;const grab=$('grabhandle'),hinge=new THREE.Vector3(0,0,2.5);
function rayAt(e){const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);return ray}
function planeAngle(e){const ray=rayAt(e);if(Math.abs(ray.ray.direction.y)<.12)return null;const q=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),new THREE.Vector3());if(!q)return null;if(params.reference)q.set(26.4-q.z,-q.y,-q.x);return Math.atan2(-q.x,q.z-2.5)*180/Math.PI}
function armHit(e){return rayAt(e).intersectObjects(meshes.filter(m=>m.visible&&(m.name.startsWith('A housing side')||m.name==='A broad cross handle')),false)[0]}
function poseAtAngle(degrees,opening){let lo=opening?.8:.1,hi=opening?1:.7;for(let i=0;i<28;i++){let mid=(lo+hi)/2,t=wholeState({...params,manual:false,pose:mid}).t*180/Math.PI;if(opening?t>degrees:t<degrees)lo=mid;else hi=mid}return(lo+hi)/2}
function beginHandle(e,explicit=false){if(e.button!==0||handleDrag||(!explicit&&!armHit(e)))return;const st=wholeState(params);motion=false;$('play').textContent='Play';params.manual=false;controls.enabled=false;handleDrag={id:e.pointerId,target:e.currentTarget,angle:st.t*180/Math.PI,rayAngle:planeAngle(e),x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);grab.textContent='↕ Moving handle';renderer.domElement.style.cursor='grabbing';e.preventDefault();e.stopImmediatePropagation()}
function moveHandle(e){if(!handleDrag){if(e.currentTarget===renderer.domElement)renderer.domElement.style.cursor=armHit(e)?'grab':'default';return}if(e.pointerId!==handleDrag.id)return;let next=planeAngle(e),delta;
 if(next!==null&&handleDrag.rayAngle!==null){delta=((next-handleDrag.rayAngle+540)%360)-180;handleDrag.rayAngle=next;}else{const t=handleDrag.angle*Math.PI/180,point=a=>viewPoint(new THREE.Vector3(-35*Math.sin(a),0,35*Math.cos(a)+2.5)).project(camera),a=point(t-.01),b=point(t+.01),dx=(b.x-a.x)*stage.clientWidth/2/.02,dy=-(b.y-a.y)*stage.clientHeight/2/.02,n=dx*dx+dy*dy;delta=n>1?((e.clientX-handleDrag.x)*dx+(e.clientY-handleDrag.y)*dy)/n*180/Math.PI:(e.clientY-handleDrag.y)*.2;}
 const desired=Math.max(100,Math.min(180,handleDrag.angle+delta));handleDrag.x=e.clientX;handleDrag.y=e.clientY;if(Math.abs(desired-handleDrag.angle)>.001){params.pose=poseAtAngle(desired,desired<handleDrag.angle);handleDrag.angle=desired;$('pose').value=params.pose;rebuild()}e.preventDefault();e.stopImmediatePropagation()}
function endHandle(e){if(!handleDrag||e.pointerId!==handleDrag.id)return;const target=handleDrag.target;handleDrag=null;controls.enabled=true;grab.textContent='↕ Drag handle';renderer.domElement.style.cursor='grab';if(target.hasPointerCapture(e.pointerId))target.releasePointerCapture(e.pointerId);e.preventDefault();e.stopImmediatePropagation()}
for(const target of [renderer.domElement,grab]){target.addEventListener('pointerdown',e=>beginHandle(e,target===grab),true);target.addEventListener('pointermove',moveHandle,true);target.addEventListener('pointerup',endHandle,true);target.addEventListener('pointercancel',endHandle,true);}
$('handleview').onclick=()=>{$('handleview').classList.add('active');$('lock').classList.remove('active');$('whole').classList.remove('active');focus='arm';reveal=false;$('transparent').checked=false;followCenter=null;$('lock').textContent='Show mechanism';isolation=false;applyVisibility();fit('arm',(params.reference?new THREE.Vector3(1,-1,.75):new THREE.Vector3(.15,-1,.1)).normalize());};
$('move').oninput=()=>{motion=false;$('play').textContent='Play';params.manual=true;const val=+$('move').value;if(selected==='actuator'||selected==='pawl')params.actuation=val;else if(selected==='runner')params.travel=val;else params.angle=val;$('movevalue').textContent=val;rebuild()};
$('pose').oninput=()=>{motion=false;$('play').textContent='Play';params.manual=false;params.pose=+$('pose').value;rebuild()};$('resetpose').onclick=()=>{motion=false;$('play').textContent='Play';params.manual=false;params.pose=0;$('pose').value=0;rebuild();fit(focus)};$('play').onclick=()=>{motion=!motion;$('play').textContent=motion?'Pause':'Play';if(motion){params.manual=false;playStart=performance.now()-params.pose*16000}};
function resize(){renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);
function render(now){requestAnimationFrame(render);$('panelplay').textContent=motion?'Pause':'Play';if(motion&&now-lastStep>65){lastStep=now;params.pose=((now-playStart)/16000)%1;$('pose').value=params.pose;rebuild();}controls.update();const t=wholeState(params).t,q=viewPoint(new THREE.Vector3(-35*Math.sin(t),-5.7,35*Math.cos(t)+2.5)).project(camera);grab.style.left=((q.x+1)*stage.clientWidth/2)+'px';grab.style.top=((1-q.y)*stage.clientHeight/2)+'px';grab.hidden=isolation||q.z>1||q.z< -1||Math.abs(q.x)>1||Math.abs(q.y)>1;renderer.setScissorTest(false);renderer.setViewport(0,0,stage.clientWidth,stage.clientHeight);renderer.render(scene,camera);
 const w=stage.clientWidth,h=stage.clientHeight;if(w>650){const cw=145,ch=185;const b=bounds('whole'),c=b.getCenter(new THREE.Vector3());contextCamera.aspect=cw/ch;contextCamera.position.copy(c).add((params.reference?new THREE.Vector3(320,-300,280):new THREE.Vector3(-260,-330,70)));contextCamera.lookAt(c);contextCamera.updateProjectionMatrix();renderer.clearDepth();renderer.setScissorTest(true);renderer.setScissor(w-cw-14,12,cw,ch);renderer.setViewport(w-cw-14,12,cw,ch);renderer.setClearColor(0xf6faf7);renderer.clear(true,true,false);renderer.render(scene,contextCamera);renderer.setScissorTest(false);renderer.setClearColor(0xe6ede9)}
}
$('layout').value=params.reference?'reference':'legacy';$('boardlabel').hidden=params.reference;if(params.reference){$('plates').value='solid';$('whole').textContent='Whole desk pad';$('contextlabel').textContent='Desk-pad context';renderer.toneMappingExposure=.9;}rebuild();resize();select('lock');focus='arm';fit('arm',(params.reference?new THREE.Vector3(1,-1,.75):new THREE.Vector3(.15,-1,.1)).normalize());playStart=performance.now()-params.pose*16000;$('play').textContent='Pause';requestAnimationFrame(render);
