const fs=require('fs'),path=require('path');
const P=__dirname,src=path.join(P,'run-001/model.snapshot.js'),{wholeState}=require(src),base=require(path.join(P,'run-001/receipt.json'));
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1],Kpad=2,rows=[];
function state(paper,rmm,degrees){const st=wholeState({manual:true,angle:degrees,travel:33-rmm,paperThickness:paper}),th=st.t,e=[Math.cos(th),Math.sin(th)],v=[st.C[0]-st.B[0],st.C[1]-st.B[1]],cp=[-st.C[1],st.C[0]],tip=st.rot([-33,42]),den=dot(v,cp);return{gap:st.gap*st.scale,dgdr:tip[0]*dot(v,e)/den,dgdt:st.scale*tip[0]*dot(v,[-st.r*e[1],st.r*e[0]])/den}}
for(const b of base.rows)for(const stop of [179,180,181]){
 const theta=stop*Math.PI/180,r=b.r_mm,s=state(b.paper_mm,r,stop),stroke=3+6.6*Math.tan(theta)-1/Math.cos(theta),ds=6.6/Math.cos(theta)**2-Math.tan(theta)/Math.cos(theta),Fr=.6+.05*(33-r),FE=.02+.02*stroke,Q=Kpad*Math.max(0,b.paper_mm+1-s.gap),R=-Fr-Q*s.dgdr,tau=Q*s.dgdt-FE*ds;
 const h=1e-6,strokeFn=t=>3+6.6*Math.tan(t)-1/Math.cos(t),dsfd=(strokeFn(theta+h)-strokeFn(theta-h))/(2*h);
 rows.push({paper_mm:b.paper_mm,stop_deg:stop,r_fixed_mm:r,overcenter_deg:stop-b.toggle_deg,gap_mm:s.gap,pad_compression_mm:Math.max(0,b.paper_mm+1-s.gap),jaw_N:Q,dgap_dr:s.dgdr,dgap_dtheta_mm_per_rad:s.dgdt,Bspring_outward_N:Fr,ideal_latch_radial_reaction_N:R,required_stroke_mm:stroke,within_declared_4mm_travel:stroke>=0&&stroke<=4+1e-10,return_spring_N:FE,ds_dtheta_mm_per_rad:ds,ds_derivative_error:Math.abs(ds-dsfd),jaw_closing_torque_Nmm:Q*s.dgdt,return_opening_torque_Nmm:FE*ds,net_closing_torque_Nmm:tau,conditional_stop_equilibrium:tau>=0,required_stop_reaction_Nmm:tau>=0?tau:null,signed_quasistatic_hand_N:-tau/40,minimum_closing_hand_to_hold_N:Math.max(0,-tau)/40,initial_opening_hand_threshold_N:Math.max(0,tau)/40});
}
const result={scope:'Conditional fixed-r latch, stipulated unilateral handle stop, assumed pad/spring laws; not solved acquisition, pawl contacts or full cycle',source_sha256:base.source_sha256,assumptions:{pad_free_mm:1,Kpad_N_per_mm:2,Bspring_preload_at_r33_N:.6,Bspring_rate_N_per_mm:.05,return_spring_preload_N:.02,return_spring_rate_N_per_mm:.02,hand_momentarm_mm:40,max_declared_actuator_stroke_mm:4},signs:'positive r outward; latch R=-Fr-Q*dgdr. Positive torque closes(theta increases), stop reaction acts negative. Return spring opposes increasingstroke. Hand force signed positiveclosing.',stroke_law:'s(theta)=3+6.6tan(theta)-sec(theta), derived from unclamped wall-contact geometry',rows};
const out=path.join(P,process.argv[2]||'conditional-stop-001');fs.mkdirSync(out);fs.writeFileSync(path.join(out,'receipt.json'),JSON.stringify(result,null,2));fs.copyFileSync(__filename,path.join(out,'conditional-stop.js'));console.log(JSON.stringify(rows,null,2));
